"""add intermediate images and passwords

Revision ID: 0c3c1d4acd39
Revises: d9e8f37a2724
Create Date: 2025-02-17 12:55:43.746394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c3c1d4acd39'
down_revision = 'd9e8f37a2724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_pipelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pose_estimation_image', postgresql.BYTEA(), nullable=True))
        batch_op.add_column(sa.Column('cropped_image', postgresql.BYTEA(), nullable=True))
        batch_op.add_column(sa.Column('dot_detection_image', postgresql.BYTEA(), nullable=True))
        batch_op.add_column(sa.Column('straightened_dots_image', postgresql.BYTEA(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_pipelines', schema=None) as batch_op:
        batch_op.drop_column('straightened_dots_image')
        batch_op.drop_column('dot_detection_image')
        batch_op.drop_column('cropped_image')
        batch_op.drop_column('pose_estimation_image')

    op.drop_table('passwords')
    # ### end Alembic commands ###
