"""initial migration

Revision ID: c2b07704da0a
Revises: 
Create Date: 2024-11-24 01:20:24.790499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2b07704da0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_image', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_pipelines.id'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sightings')
    op.drop_table('individuals')
    op.drop_table('image_pipelines')
    # ### end Alembic commands ###
