"""add locations

Revision ID: d9e8f37a2724
Revises: c2b07704da0a
Create Date: 2024-12-01 13:08:06.903610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e8f37a2724'
down_revision = 'c2b07704da0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('named_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('precise_location', sa.ARRAY(sa.Float()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('precise_location', sa.ARRAY(sa.Float()), nullable=True))
        batch_op.create_foreign_key(None, 'named_locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('precise_location')
        batch_op.drop_column('location_id')

    op.drop_table('named_locations')
    # ### end Alembic commands ###
