"""add intermediate images

Revision ID: f0a259fef2ff
Revises: d9e8f37a2724
Create Date: 2025-01-30 16:10:56.770947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0a259fef2ff'
down_revision = 'd9e8f37a2724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_pipelines', schema=None) as batch_op:
        batch_op.alter_column('pose_estimation_image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('cropped_image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('dot_detection_image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('straightened_dots_image',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_pipelines', schema=None) as batch_op:
        batch_op.alter_column('straightened_dots_image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('dot_detection_image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('cropped_image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('pose_estimation_image',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
