import matplotlib.pyplot as plt

# file to read a file with lines obtained while training, to visualise
# the evolution of training loss
# generated by ChatGPT

# Initialize lists to store iterations and loss values
iterations = []
loss_values = []

# Open and read the file
with open('loss_data.txt', 'r') as file:
    for line in file:
        # Split the line by spaces
        parts = line.split()

        # Extract iteration number and loss value
        iteration = int(parts[1])
        loss = float(parts[3])

        # Append the extracted data to the respective lists
        iterations.append(iteration)
        loss_values.append(loss)

# Plotting the loss over iterations
plt.figure(figsize=(10, 6))
plt.plot(iterations, loss_values, marker='o', linestyle='-', color='b')

# Adding title and labels
plt.title('Loss over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Loss')

# Display the plot
plt.grid(True)
plt.show()
